services:
  auth-service:
    build: .
    container_name: auth-service
    ports:
      - "8082:8082"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=supersecretkey
    depends_on:
      - redis
