services:
  match-service:
    build:
      context: ./match-service
    container_name: match-service
    ports:
      - "8083:8083"
    environment:
      - NEO4J_URI=neo4j://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=SS29lose
    depends_on:
      - neo4j
    networks:
      - shared-network

networks:
  shared-network:
    external: true



